import type { Metadata } from "next";
import { Bricolage_Grotesque, Fira_Mono } from "next/font/google";
import "./globals.css";

const bricolage_Grotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-sans",
  subsets: ["latin"],
});

const fira_mono = Fira_Mono({
  variable: "--font-fira-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Application for Tau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage_Grotesque.variable} ${fira_mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
